/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)/': RouteRecordInfo<'/(home)/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/401': RouteRecordInfo<'/401', '/401', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/[id]': RouteRecordInfo<'/about/[id]', '/about/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/about/[id]/': RouteRecordInfo<'/about/[id]/', '/about/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/about/detail/[id]': RouteRecordInfo<'/about/detail/[id]', '/about/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/auth/signin': RouteRecordInfo<'/auth/signin', '/auth/signin', Record<never, never>, Record<never, never>>,
    '/callback/': RouteRecordInfo<'/callback/', '/callback', Record<never, never>, Record<never, never>>,
    '/callback/[time]': RouteRecordInfo<'/callback/[time]', '/callback/:time', { time: ParamValue<true> }, { time: ParamValue<false> }>,
    '/cart/': RouteRecordInfo<'/cart/', '/cart', Record<never, never>, Record<never, never>>,
    '/cart/failed': RouteRecordInfo<'/cart/failed', '/cart/failed', Record<never, never>, Record<never, never>>,
    '/cart/success': RouteRecordInfo<'/cart/success', '/cart/success', Record<never, never>, Record<never, never>>,
    '/user-console/bare-metal/': RouteRecordInfo<'/user-console/bare-metal/', '/user-console/bare-metal', Record<never, never>, Record<never, never>>,
    '/user-console/bare-metal/[id]': RouteRecordInfo<'/user-console/bare-metal/[id]', '/user-console/bare-metal/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/user-console/bare-metal/create/': RouteRecordInfo<'/user-console/bare-metal/create/', '/user-console/bare-metal/create', Record<never, never>, Record<never, never>>,
    '/user-console/resource-overview/': RouteRecordInfo<'/user-console/resource-overview/', '/user-console/resource-overview', Record<never, never>, Record<never, never>>,
    '/user-console/template/': RouteRecordInfo<'/user-console/template/', '/user-console/template', Record<never, never>, Record<never, never>>,
  }
}
