/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../pages/__root'
import { Route as AboutRouteImport } from './../pages/about/route'
import { Route as HelloIndexImport } from './../pages/hello/index'
import { Route as AboutIndexImport } from './../pages/about/index'
import { Route as HelloIdImport } from './../pages/hello/$id'
import { Route as AboutAboutIdImport } from './../pages/about/$aboutId'

// Create/Update Routes

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const HelloIndexRoute = HelloIndexImport.update({
  id: '/hello/',
  path: '/hello/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)

const HelloIdRoute = HelloIdImport.update({
  id: '/hello/$id',
  path: '/hello/$id',
  getParentRoute: () => rootRoute,
} as any)

const AboutAboutIdRoute = AboutAboutIdImport.update({
  id: '/$aboutId',
  path: '/$aboutId',
  getParentRoute: () => AboutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/about/$aboutId': {
      id: '/about/$aboutId'
      path: '/$aboutId'
      fullPath: '/about/$aboutId'
      preLoaderRoute: typeof AboutAboutIdImport
      parentRoute: typeof AboutRouteImport
    }
    '/hello/$id': {
      id: '/hello/$id'
      path: '/hello/$id'
      fullPath: '/hello/$id'
      preLoaderRoute: typeof HelloIdImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof AboutRouteImport
    }
    '/hello/': {
      id: '/hello/'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AboutRouteRouteChildren {
  AboutAboutIdRoute: typeof AboutAboutIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutAboutIdRoute: AboutAboutIdRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRouteRouteWithChildren
  '/about/$aboutId': typeof AboutAboutIdRoute
  '/hello/$id': typeof HelloIdRoute
  '/about/': typeof AboutIndexRoute
  '/hello': typeof HelloIndexRoute
}

export interface FileRoutesByTo {
  '/about/$aboutId': typeof AboutAboutIdRoute
  '/hello/$id': typeof HelloIdRoute
  '/about': typeof AboutIndexRoute
  '/hello': typeof HelloIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/about/$aboutId': typeof AboutAboutIdRoute
  '/hello/$id': typeof HelloIdRoute
  '/about/': typeof AboutIndexRoute
  '/hello/': typeof HelloIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/about/$aboutId' | '/hello/$id' | '/about/' | '/hello'
  fileRoutesByTo: FileRoutesByTo
  to: '/about/$aboutId' | '/hello/$id' | '/about' | '/hello'
  id:
    | '__root__'
    | '/about'
    | '/about/$aboutId'
    | '/hello/$id'
    | '/about/'
    | '/hello/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  HelloIdRoute: typeof HelloIdRoute
  HelloIndexRoute: typeof HelloIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRouteRoute: AboutRouteRouteWithChildren,
  HelloIdRoute: HelloIdRoute,
  HelloIndexRoute: HelloIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/hello/$id",
        "/hello/"
      ]
    },
    "/about": {
      "filePath": "about/route.tsx",
      "children": [
        "/about/$aboutId",
        "/about/"
      ]
    },
    "/about/$aboutId": {
      "filePath": "about/$aboutId.tsx",
      "parent": "/about"
    },
    "/hello/$id": {
      "filePath": "hello/$id.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx",
      "parent": "/about"
    },
    "/hello/": {
      "filePath": "hello/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
